name: Hello World

on:
  push:
    branches:
      - main  # O la rama que estés usando

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "¡Hola, mundo!"
